# Generated by Django 4.2.1 on 2023-06-07 20:43

import city_manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonform.models.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("scene", models.TextField(blank=True, null=True)),
                ("streets_description", models.TextField(blank=True, null=True)),
                (
                    "streets",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                ("buildings_description", models.TextField(blank=True, null=True)),
                (
                    "traits",
                    django_jsonform.models.fields.ArrayField(
                        base_field=django_jsonform.models.fields.ArrayField(
                            base_field=models.CharField(max_length=100), size=None
                        ),
                        size=None,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city_manager.city",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("tier", models.PositiveIntegerField(default=0)),
                (
                    "hold",
                    models.CharField(
                        choices=[("w", "weak"), ("s", "strong")],
                        default="w",
                        max_length=1,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "turf",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assets",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("quirks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city_manager.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("clock_ticks", models.PositiveBigIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Landmark",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city_manager.district",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictFaction",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city_manager.district",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city_manager.faction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="city_manager.world"
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "adjectives",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="city_manager.district",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city_manager.faction",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "people",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="city_manage_is_acti_4e7015_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FactionFactionRelation",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_reputation", models.IntegerField(default=0)),
                (
                    "source_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_source_faction",
                        to="city_manager.faction",
                    ),
                ),
                (
                    "target_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_target_faction",
                        to="city_manager.faction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_faction"], name="city_manage_source__0490d9_idx"
                    )
                ],
                "unique_together": {("source_faction", "target_faction")},
            },
        ),
        migrations.CreateModel(
            name="FactionClock",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("max_segments", models.PositiveIntegerField(default=4)),
                ("completed_segments", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "objective_type",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                city_manager.models.ClockObjectiveType["ACQUIRE_ASSET"],
                            ),
                            (
                                2,
                                city_manager.models.ClockObjectiveType["CONTEST_RIVAL"],
                            ),
                            (3, city_manager.models.ClockObjectiveType["AID_ALLY"]),
                            (4, city_manager.models.ClockObjectiveType["REMOVE_RIVAL"]),
                            (5, city_manager.models.ClockObjectiveType["EXPAND_GANG"]),
                            (
                                6,
                                city_manager.models.ClockObjectiveType[
                                    "CLAIM_TERRITORY"
                                ],
                            ),
                        ],
                        default=city_manager.models.ClockObjectiveType["ACQUIRE_ASSET"],
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clock_source_faction",
                        to="city_manager.faction",
                    ),
                ),
                (
                    "target_faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clock_target_faction",
                        to="city_manager.faction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["completed"], name="city_manage_complet_4b3ff1_idx"
                    ),
                    models.Index(
                        fields=["faction"], name="city_manage_faction_d10afd_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="faction",
            index=models.Index(
                fields=["is_active"], name="city_manage_is_acti_07296d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="districtfaction",
            unique_together={("district", "faction")},
        ),
    ]
