# Generated by Django 4.2.1 on 2023-06-07 21:13

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0001_setup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="streets",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
