# Generated by Django 3.2.4 on 2023-05-12 02:16

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='streets',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='district',
            name='traits',
            field=django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='faction',
            name='assets',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='faction',
            name='turf',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='adjectives',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
