# Generated by Django 4.2.1 on 2023-06-07 17:47

import city_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0001_setup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factionclock",
            name="objective_type",
            field=models.IntegerField(
                choices=[
                    (
                        city_manager.models.ClockObjectiveType["ACQUIRE_ASSET"],
                        "acquire asset",
                    ),
                    (
                        city_manager.models.ClockObjectiveType["CONTEST_RIVAL"],
                        "contest rival",
                    ),
                    (city_manager.models.ClockObjectiveType["AID_ALLY"], "aid ally"),
                    (
                        city_manager.models.ClockObjectiveType["REMOVE_RIVAL"],
                        "remove rival",
                    ),
                    (
                        city_manager.models.ClockObjectiveType["EXPAND_GANG"],
                        "expand gang",
                    ),
                    (
                        city_manager.models.ClockObjectiveType["CLAIM_TERRITORY"],
                        "claim territory",
                    ),
                ],
                default=city_manager.models.ClockObjectiveType["ACQUIRE_ASSET"],
            ),
        ),
    ]
