# Generated by Django 4.2.1 on 2023-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0002_optional_streetnames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faction",
            name="category",
        ),
        migrations.AddField(
            model_name="faction",
            name="current_situation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faction",
            name="assets",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faction",
            name="hold",
            field=models.CharField(
                choices=[("w", "weak"), ("s", "strong")], default="s", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="turf",
            field=models.TextField(blank=True, null=True),
        ),
    ]
