# Generated by Django 3.2.4 on 2023-05-12 02:36

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city_manager', '0002_update_arrayfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonplayercharacter',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='city_manager.faction'),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='adjectives',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='city_manager.district'),
        ),
    ]
