# Generated by Django 3.2.4 on 2023-05-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0002_add_factions_and_districts"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactionFactionRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
