# Generated by Django 4.2.1 on 2023-06-07 20:02

import city_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0003_timestamp_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factionclock",
            name="objective_type",
            field=models.IntegerField(
                choices=[
                    (1, city_manager.models.ClockObjectiveType["ACQUIRE_ASSET"]),
                    (2, city_manager.models.ClockObjectiveType["CONTEST_RIVAL"]),
                    (3, city_manager.models.ClockObjectiveType["AID_ALLY"]),
                    (4, city_manager.models.ClockObjectiveType["REMOVE_RIVAL"]),
                    (5, city_manager.models.ClockObjectiveType["EXPAND_GANG"]),
                    (6, city_manager.models.ClockObjectiveType["CLAIM_TERRITORY"]),
                ],
                default=city_manager.models.ClockObjectiveType["ACQUIRE_ASSET"],
            ),
        ),
    ]
