# Generated by Django 4.2.1 on 2023-06-07 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0003_faction_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="city_manager.city",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="landmark",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="city_manager.district",
            ),
        ),
    ]
