# Generated by Django 4.2.1 on 2023-07-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0005_string_and_options_cleanup_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="hold",
            field=models.IntegerField(choices=[(0, "Weak"), (1, "Strong")], default=1),
        ),
    ]
