# Generated by Django 4.2.1 on 2023-05-18 19:22

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0005_add_faction_clocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("step", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="factionclock",
            name="clock_segments",
        ),
        migrations.AddField(
            model_name="faction",
            name="is_dead_or_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factionclock",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factionclock",
            name="completed_segments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factionclock",
            name="max_segments",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="nonplayercharacter",
            name="is_dead_or_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="faction",
            name="assets",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="tier",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
