# Generated by Django 4.2.1 on 2023-07-12 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0006_string_and_options_cleanup_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faction",
            name="hold_string",
        ),
    ]
