# Generated by Django 4.2.1 on 2023-05-27 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0007_update_objective_types_definition"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NonPlayerCharacter",
            new_name="Person",
        ),
    ]
