# Generated by Django 4.2.1 on 2023-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0008_rename_npc_to_person"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="districtfaction",
            unique_together={("district", "faction")},
        ),
        migrations.AlterUniqueTogether(
            name="factionfactionrelation",
            unique_together={("source_faction", "target_faction")},
        ),
        migrations.AddIndex(
            model_name="faction",
            index=models.Index(
                fields=["is_dead_or_deleted"], name="city_manage_is_dead_466f02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factionclock",
            index=models.Index(
                fields=["completed"], name="city_manage_complet_4b3ff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factionclock",
            index=models.Index(
                fields=["faction"], name="city_manage_faction_d10afd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factionfactionrelation",
            index=models.Index(
                fields=["source_faction"], name="city_manage_source__0490d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["is_dead_or_deleted"], name="city_manage_is_dead_2ef50a_idx"
            ),
        ),
    ]
