# Generated by Django 4.2.1 on 2023-06-02 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0009_index_tables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "people"},
        ),
    ]
