# Generated by Django 4.2.1 on 2023-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_manager", "0010_add_verbose_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="step",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calendar",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
