# Generated by Django 4.2.1 on 2023-06-05 19:31

from django.db import migrations, models
import django.db.models.deletion

from city_manager.models import Calendar


class CalendarObjectHolder:
    @classmethod
    def get_object_id(cls):
        return cls.calendar_object.id

    @classmethod
    def get(cls, apps, schema_editor):
        Calendar = apps.get_model("city_manager", "Calendar")
        db_alias = schema_editor.connection.alias
        cls.calendar_object = Calendar.objects.first()
        if isinstance(cls.calendar_object, type(None)):
            cls.calendar_object = Calendar.objects.create()
            cls.calendar_object.save()


class Migration(migrations.Migration):
    def get_calendar():
        try:
            calendar = Calendar.objects.first()
        except Calendar.DoesNotExist:
            calendar = Calendar()
            calendar.save()
        return calendar

    dependencies = [
        ("city_manager", "0011_reset_pk_on_calendars"),
    ]

    operations = [
        migrations.RunPython(CalendarObjectHolder.get),
        migrations.AddField(
            model_name="city",
            name="calendar",
            field=models.ForeignKey(
                default=CalendarObjectHolder.get_object_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="city_manager.calendar",
            ),
        ),
    ]
